### ISSUE TITLE
Get aerosol optical depth from NASA climatology

### ISSUE THREAD

**Issue by ateucher** [bcgov/pahwq#3]
Get optical thickness monthly averages (for 1x1 degree grid boxes) from here: https://gacp.giss.nasa.gov/datasets/ and populate for the given day (actual data files here: https://gacp.giss.nasa.gov/data/time_ser/)

**Comment by ateucher** [comment]
@atillmanns The NASA data has average monthly aerosol optical depth (tau) values per year from 1981 to 2009. I assume most of the time we will be calculating WQG for a date more recent than that, so do you think I should calculate monthly average aerosol values across all years, and then for a WQG calculation, we would be using an average aerosol value for that month at the given latitude and longitude?

**Comment by ateucher** [comment]
Note: Daily values from 2012-present are available here: https://neo.gsfc.nasa.gov/archive/csv/MODAL2_D_AER_OD/. They would have to be downloaded and processed on the fly as they are too large to store in the package.

This is doable, but will be slow to run and requires an internet connection.

They could also be downloaded and preprocessed and stored in the package if we are ok to use averages...

**Comment by ateucher** [comment]
The historical data from [the gacp site](https://gacp.giss.nasa.gov/data/time_ser/) seems to have poor coverage over land??

(white areas are missing data)
``` r
url <- "https://gacp.giss.nasa.gov/data/time_ser/0907.tau.ascii.gz"

temp_file <- tempfile(fileext = ".ascii.gz")

download.file(url, destfile = temp_file)

f <- gzfile(temp_file)

d <- as.matrix(read.delim(f, sep = "", header = FALSE, skip = 1))

# NA are encoded as -1
d[d < 0] <- NA

image(t(apply(d, 2, rev)))
```

![](https://i.imgur.com/VWaoGlK.png)

<sup>Created on 2023-11-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ateucher** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PAH sensitivity meeting](https://trello.com/c/rYySYP7u/76-pah-sensitivity-meeting)

**Comment by ateucher** [comment]
Reopening as the functionality is implemented via #4, but we need to resolve the data source

**Comment by atillmanns** [comment]
Is it possible to tell if the data from the NASA/Aeronet site https://aeronet.gsfc.nasa.gov/new_web/data.html has good coverage over Canada and the coastline?  If so, then yes, use this data source.  And monthly averages make sense.

**Comment by ateucher** [comment]
Looking more at the aeronet site, it looks like that is site-specific ground-based measurements, so the data are only available at the monitoring sites. The data from [here](https://neo.gsfc.nasa.gov/view.php?datasetId=MODAL2_M_AER_OD) looks to be satellite based and provides broad coverage
